captiveportal/captiveportal/urls.py
# Copyright (C) 2021 Grant Emsley <grant@emsley.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""captiveportal URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from .local_urls import urlpatterns as local_urls

admin.site.site_header = 'Captive Portal Voucher Manager'
admin.site.site_title = 'Captive Portal Voucher Manager'

urlpatterns = [
    path('', include('voucher.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += local_urls

captiveportal/voucher/urls.py
# Copyright (C) 2021 Grant Emsley <grant@emsley.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path
from . import views

app_name = 'voucher'

urlpatterns = [
    path('', views.PortalListView.as_view(), name='index'),
    path('portals/<int:portal_id>/', views.printselection, name='portal'),
    path('print/<int:portal_id>/<int:roll_id>/<int:printtemplate_id>/', views.print, name='print'),
]

captiveportal/voucher/models.py
# Copyright (C) 2021 Grant Emsley <grant@emsley.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.db import models
from django.contrib.auth.models import Group

class PrintTemplate(models.Model):
    PRINT_TYPE_CHOICES = [
        ('Dymo', 'Dymo Labelwriter'),
        ('Paper', 'Regular Paper'),
    ]
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=16,choices=PRINT_TYPE_CHOICES,default="Paper")
    template = models.TextField(help_text="""<p>For regular paper templates, the template is a block of HTML that will be repeated once for each voucher code. The following text will be substituted in the template:</p>
        <ul>
            <li>#PORTALNAME# - The name of the portal
            <li>#SSID# - SSID set in the portal
            <li>#PSK# - Password set in the portal
            <li>#CODE# - The voucher code for this voucher
            <li>#TIMELIMIT# - The time limit set in the roll
            <li>#ROLLNUMBER# - The roll number
            <li>#ROLLDESCRIPTION# - The description of the roll
            <li>#LOOPCOUNTER# - The number of the ticket from this print job. Useful for creating unique HTML IDs
        </ul>
        <p>For Dymo Labelwriter templates, the template is a valid Dymo XML file. The following objects will be replaced with their corresponding values:</p>
        <ul>
            <li>PortalName
            <li>SSID
            <li>PSK
            <li>TimeLimit
            <li>VoucherCode
            <li>QRCode - replaced with the QR string to connect to the network, eg. WIFI:T:WPA;S:MySSID;P:MyPresharedKey;;
        </ul>
        <p>Note: The Dymo library does not properly parse Color tags without any content in them. Add a space between the opening and closing Color tags if you get an error.</p>
    """)

    def __str__(self):
        return self.name

class Portal(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    ssid = models.CharField(max_length=32, blank=True)
    psk = models.CharField(max_length=64, blank=True)
    active = models.BooleanField(default=True)
    allow_printing = models.ManyToManyField(Group, blank=True)
    print_templates = models.ManyToManyField(PrintTemplate, blank=False)

    def __str__(self):
        return self.name

    def roll_count(self):
        return self.roll_set.count()

    def available_rolls(self):
        return self.roll_set.filter(active=True)

class Roll(models.Model):
    portal = models.ForeignKey(Portal, on_delete=models.CASCADE)
    number = models.IntegerField()
    description = models.CharField(max_length=200)
    time_limit = models.CharField(max_length=200)
    active = models.BooleanField(default=True)
    voucher_csv = models.FileField(null=True,blank=True)

    def __str__(self):
        return "%s - %s" %(self.portal.name, self.description)

    def save(self, *args, **kwargs):
        """Save the database record and file, then process the file and delete it."""
        super(Roll, self).save(*args, **kwargs)
        if self.voucher_csv and hasattr(self.voucher_csv, 'url'):
            voucherfile = self.voucher_csv.open(mode='r')
            for line in voucherfile.read().splitlines():
                if line.startswith("#"):
                    continue

                vouchercode = line.strip("\" ")

                # Skip vouchers that already exist in the database.
                if(Voucher.objects.filter(code=vouchercode).exists()):
                    continue

                self.voucher_set.create(code=vouchercode)

            self.voucher_csv.delete()


    def total_vouchers(self):
        return self.voucher_set.count()

    def remaining_vouchers(self):
        return self.voucher_set.filter(date_printed__isnull=True).count()

class Voucher(models.Model):
    roll = models.ForeignKey(Roll, on_delete=models.CASCADE)
    code = models.CharField(max_length=30, unique=True)
    date_printed = models.DateTimeField('date printed', null=True, blank=True)
    printed_by = models.CharField(max_length=200, blank=True)

    def portal(self):
        return self.roll.portal.name

captiveportal/voucher/views.py
# Copyright (C) 2021 Grant Emsley <grant@emsley.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
import datetime
from django.utils import timezone
from urllib.parse import urlencode
from .models import Portal, Roll, Voucher, PrintTemplate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.contrib import messages



def redirect_params(url, params=None):
    response = redirect(url)
    if params:
        query_string = urlencode(params, True)
        response['Location'] += '?' + query_string
    return response


class PortalListView(LoginRequiredMixin, generic.ListView):
    model = Portal

    def get_queryset(self):
        # Limit only to active portals
        qs = super().get_queryset()
        qs = qs.filter(active=True)

        # Hide portals where the user has no groups that are allowed printing.
        groups = self.request.user.groups.values_list('id', flat=True)
        qs = qs.filter(allow_printing__in=groups)

        # Groups query can cause duplicate records.
        qs = qs.distinct()

        return qs


@login_required
def printselection(request, portal_id):
    
    # Make sure the portal is active and user has access.
    groups = request.user.groups.values_list('id', flat=True)
    try:
        portal = Portal.objects.filter(pk=portal_id,active=True,allow_printing__in=groups).distinct().get()
    except Portal.DoesNotExist:
        raise Http404("Portal does not exist")


    if request.method == 'POST':
        printtemplate_id = request.POST['printtemplate_id']
        quantity = int(request.POST['quantity'])
        roll_id = int(request.POST['roll_id'])

        roll = get_object_or_404(Roll, pk=roll_id)
        printtemplate = get_object_or_404(PrintTemplate, pk=printtemplate_id)

        # Validate parameters
        if (quantity < 1):
            messages.add_message(request, messages.ERROR, 'Invalid quantity.')
            return render(request, 'voucher/print_selection.html', {'portal':portal, 'printtemplate_id':printtemplate_id, 'quantity':quantity, 'roll_id': roll_id})
        if (quantity > roll.remaining_vouchers()):
            messages.add_message(request, messages.ERROR, 'Not enough vouchers available.')
            return render(request, 'voucher/print_selection.html', {'portal':portal, 'printtemplate_id':printtemplate_id, 'quantity':quantity, 'roll_id': roll_id})
            
        # Get only unprinted vouchers from this roll
        vouchers = Voucher.objects.filter(roll=roll.id)
        vouchers = vouchers.filter(date_printed__isnull=True)
        # Retrieve the id values as a flat list (convert to list(), otherwise the query will change when we update these values!)
        vouchers = list(vouchers.values_list('id', flat=True)[:quantity])

        # Mark these vouchers as printed
        Voucher.objects.filter(id__in=vouchers).update(date_printed=timezone.now(),printed_by=request.user.get_username())

        return redirect_params(reverse('voucher:print', kwargs={'portal_id': portal_id, 'roll_id': roll_id, 'printtemplate_id': printtemplate_id}), {'v': vouchers})
    else:
        return render(request, 'voucher/print_selection.html', {'portal':portal,'quantity':5})

@login_required
def print(request, portal_id, roll_id, printtemplate_id):
    # Make sure the portal is active and user has access.
    groups = request.user.groups.values_list('id', flat=True)
    try:
        portal = Portal.objects.filter(pk=portal_id,active=True,allow_printing__in=groups).distinct().get()
    except Portal.DoesNotExist:
        raise Http404("Portal does not exist")

    roll = get_object_or_404(Roll, pk=roll_id)
    printtemplate = get_object_or_404(PrintTemplate, pk=printtemplate_id)
    
    # Retrieve the vouchers by id, and verify they are ok to print (someone could have altered GET string)
    # Make sure they match the roll, and were marked as printed within the last hour
    voucherlist = request.GET.getlist('v')
    vouchers = Voucher.objects.filter(id__in=voucherlist)
    vouchers = vouchers.filter(roll=roll.id)
    vouchers = vouchers.filter(date_printed__isnull=False)
    last_hour = timezone.now() - datetime.timedelta(hours=1)
    vouchers = vouchers.filter(date_printed__gt=last_hour)
    codes = list(vouchers.values_list('code', flat=True))

    context = {
        'roll': roll,
        'portal': portal,
        'printtemplate': printtemplate,
        'codes': codes,
    }

    if printtemplate.type == "Paper":
        return render(request, 'voucher/print_paper.html', context)
    elif printtemplate.type == "Dymo":
        return render(request, 'voucher/print_dymo.html', context)
    else:
        raise Http404("Invalid print template type")    

captiveportal/voucher/templates/voucher/portal_list.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'voucher/style.css' %}">
{% endblock %}


{% block content%}
<h1>Choose Portal:</h1>
{% if object_list %}
    <ul>
        {% for portal in object_list %}
            <li><a href="{% url 'voucher:portal' portal.id %}">{{portal.name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No portals are configured or you do not have permissions to any portal.</p>
{% endif %}
{% endblock %}

captiveportal/voucher/templates/voucher/print_dymo.html
{% extends "base.html" %}
{% load static %}
{% block title %}Voucher Print{% endblock %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "voucher/style.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/forms.css" %}">
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="{% url 'voucher:portal' portal.pk %}">{{ portal.name }}</a>
&rsaquo; <span>Print</span>
</div>
{% endblock %}


{% block head %}
<script src="{% static 'voucher/dymo.connect.framework.js' %}" type="text/javascript" charset="UTF-8"></script>
<script type="text/javascript">
(function()
{

    // Note: Dymo has a bug where you need to have a space between the <Color blah> and </Color> tags or it throws an error.
    var labelxml = `{{printtemplate.template|safe}}`;

    var label = dymo.label.framework.openLabelXml(labelxml);
    label.setObjectText("PortalName", "{{ portal.name }}");
    label.setObjectText("SSID", "{{ portal.ssid }}");
    label.setObjectText("PSK", "{{ portal.psk }}");
    label.setObjectText("TimeLimit", "{{ roll.time_limit }}");
    label.setObjectText("VoucherCode", "CODE INSERTED HERE");

    // QR codes are in the format: WIFI:T:WPA;S:<ssid>;P:<PSK>;;
    // see https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11 for details
    label.setObjectText("QRCode", "WIFI:T:WPA;S:{{portal.ssid}};P:{{portal.psk}};;");

    // called when the document completly loaded
    function onload()
    {
        var printButton = document.getElementById('printButton');
        var printersSelect = document.getElementById('printersSelect');
        var printPreviewButton = document.getElementById('printPreviewButton');

        // Generates label preview and updates corresponend <img> element
        // Note: this does not work in IE 6 & 7 because they don't support data urls
        // if you want previews in IE 6 & 7 you have to do it on the server side
        function updatePreview() {
            if (!label)
                return;

            var pngData = label.render();

            var labelImage = document.getElementById('labelImage');
            labelImage.src = "data:image/png;base64," + pngData;
        }

        // loads all supported printers into a combo box 
        function loadPrinters() {
            var printers = dymo.label.framework.getPrinters();
            if (printers.length == 0) {
                alert("No DYMO printers are installed. Install DYMO printers.");
                return;
            }

            for (var i = 0; i < printers.length; i++) {
                var printer = printers[i];
                if (printer.printerType == "LabelWriterPrinter") {
                    var printerName = printer.name;

                    var option = document.createElement('option');
                    option.value = printerName;
                    option.appendChild(document.createTextNode(printerName));
                    printersSelect.appendChild(option);
                }
            }
        }

        // prints the label
        printButton.onclick = function()
        {
            try
            {

                // create label set to print data
                var labelSetBuilder = new dymo.label.framework.LabelSetBuilder();

                // Get all the child elements of voucher_codes and add them to the records
                voucher_codes = document.getElementById("voucher_codes");
                
                for(var i = 0; i < voucher_codes.children.length; i++) {
                    record = labelSetBuilder.addRecord();
                    record.setText("VoucherCode", voucher_codes.children[i].textContent);
                }

                // finally print the label with default print params
                label.print(printersSelect.value, "", labelSetBuilder);
            }
            catch(e)
            {
                alert(e.message || e);
            }
        }

        loadPrinters();
        updatePreview();

    };

    function initTests()
	{
		if(dymo.label.framework.init)
		{
			//dymo.label.framework.trace = true;
			dymo.label.framework.init(onload);
		} else {
			onload();
		}
	}

	// register onload event
	if (window.addEventListener)
		window.addEventListener("load", initTests, false);
	else if (window.attachEvent)
		window.attachEvent("onload", initTests);
	else
		window.onload = initTests;

} ());
</script>
{% endblock %}

{% block content%}
    <fieldset class="module aligned">
        <div class="form-row">
            <div id="labelImageDiv">
                <img id="labelImage" src="" label="label preview"/>
            </div>
        </div>
        <div class="form-row">
            <div>
                <label for="quantity">Printing:</label>
                <p id="quantity">{{codes|length}} voucher labels</p>
            </div>
        </div>
        <div class="form-row">
            <div id="printersDiv">
                <label for="printersSelect">Label Printer:</label>
                    <select id="printersSelect"></select>
            </div>
        </div>
        <div class="form-row">
            <div>
                <label for="printButton"></label>
                <button class="button" id="printButton">Print to Label printer</button>
            </div>
        </div>
    </fieldset>


    <div style="display:none" id="voucher_codes">
        {% for code in codes %}
            <span>{{code}}</span>
        {% endfor %}
    </div>

{% endblock %}

captiveportal/voucher/templates/voucher/print_paper.html
{%load static %}
{%load voucher %}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>Vouchers</title>
    <link rel="stylesheet" type="text/css" href="{% static "voucher/style.css" %}">
    <script src="{% static 'voucher/qrcode.min.js' %}" type="text/javascript" charset="UTF-8"></script>

    <script type="text/javascript">
        window.onload = function() {
            window.print();
        }
    </script>

</head>
<body>
{% for code in codes %}
    {% voucher printtemplate.template code forloop.counter %}
{% endfor %}
</body>
</html>

captiveportal/voucher/templates/voucher/print_selection.html
{% extends "base.html" %}
{% load static %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "voucher/style.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/forms.css" %}">

{% endblock %}
{% block title %}Voucher Type Selection{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/">Home</a>
&rsaquo; <a href="{% url 'voucher:portal' portal.pk %}">{{ portal.name }}</a>
</div>
{% endblock %}


{% block content%}

<h1>Portal Information:</h1>
<table>
    <tr>
        <th>Name:</th>
        <td>{{portal.name}}</td>
    </tr>
    <tr>
        <th>Location:</th>
        <td>{{portal.location}}</td>
    </tr>
    <tr>
        <th>SSID:</th>
        <td>{{portal.ssid}}</td>
    </tr>
    <tr>
        <th>Password:</th>
        <td>{{portal.psk}}</td>
    </tr>
</table>

<h1>Choose vouchers to print:</h1>
{% if portal.available_rolls %}
    <form action="" method="POST">
    {%csrf_token%}
    <div>
        <fieldset class="module aligned">
            <h2>Choose vouchers to print</h2>
            <div class="form-row field-roll">
                <div>
                    <label class="required" for="roll_id">Voucher type</label>
                    <select id="roll_id" name="roll_id">
                       {% for roll in portal.available_rolls %}
                            <option {%if roll.id == roll_id %}selected="selected"{%endif%} value="{{roll.id}}">{{roll.description}} - {{roll.time_limit}} - {{roll.remaining_vouchers}} available</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row field-printer-type">
                <div>
                    <label class="required" for="printtemplate_id">Print template</label>
                    <select name="printtemplate_id">
                        {% for template in portal.print_templates.all %}
                            <option {% if printtemplate_id == template.id %}selected="selected"{%endif%} value="{{template.id}}">{{template.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row field-quantity">
                <div>
                    <label class="required" for="quantity">Quantity</label>
                    <input type="number" name="quantity" id="quantity" min="1" max="100" value="{{quantity}}" />
                    <div class="help">Once you click print the vouchers will be marked as used and cannot be printed again. 
                        If you are unsure your printer is working properly, try only printing 1 or 2 vouchers so not many get wasted.
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="Print">
        </div>
    </div> 
    </form>
{% else %}
    <p>No voucher types are available for this portal. Please ask IT to issue more vouchers.</p>
{% endif %}


{% endblock %}